/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommentDTO } from './CommentDTO';
import {
    CommentDTOFromJSON,
    CommentDTOFromJSONTyped,
    CommentDTOToJSON,
} from './CommentDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CommentDTORequestResponse
 */
export interface CommentDTORequestResponse {
    /**
     * 
     * @type {CommentDTO}
     * @memberof CommentDTORequestResponse
     */
    response?: CommentDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CommentDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CommentDTORequestResponse interface.
 */
export function instanceOfCommentDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommentDTORequestResponseFromJSON(json: any): CommentDTORequestResponse {
    return CommentDTORequestResponseFromJSONTyped(json, false);
}

export function CommentDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CommentDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CommentDTORequestResponseToJSON(value?: CommentDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CommentDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

