/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentAddDTO
 */
export interface CommentAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentAddDTO
     */
    postId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentAddDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentAddDTO
     */
    content?: string | null;
}

/**
 * Check if a given object implements the CommentAddDTO interface.
 */
export function instanceOfCommentAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommentAddDTOFromJSON(json: any): CommentAddDTO {
    return CommentAddDTOFromJSONTyped(json, false);
}

export function CommentAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postId': !exists(json, 'postId') ? undefined : json['postId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function CommentAddDTOToJSON(value?: CommentAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postId': value.postId,
        'userId': value.userId,
        'content': value.content,
    };
}

