/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { EventDTOPagedResponse } from './EventDTOPagedResponse';
import {
    EventDTOPagedResponseFromJSON,
    EventDTOPagedResponseFromJSONTyped,
    EventDTOPagedResponseToJSON,
} from './EventDTOPagedResponse';

/**
 * 
 * @export
 * @interface EventDTOPagedResponseRequestResponse
 */
export interface EventDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {EventDTOPagedResponse}
     * @memberof EventDTOPagedResponseRequestResponse
     */
    response?: EventDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof EventDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the EventDTOPagedResponseRequestResponse interface.
 */
export function instanceOfEventDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventDTOPagedResponseRequestResponseFromJSON(json: any): EventDTOPagedResponseRequestResponse {
    return EventDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function EventDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : EventDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function EventDTOPagedResponseRequestResponseToJSON(value?: EventDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': EventDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

