/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventUpdateDTO
 */
export interface EventUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof EventUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EventUpdateDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventUpdateDTO
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdateDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdateDTO
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdateDTO
     */
    date?: string | null;
}

/**
 * Check if a given object implements the EventUpdateDTO interface.
 */
export function instanceOfEventUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventUpdateDTOFromJSON(json: any): EventUpdateDTO {
    return EventUpdateDTOFromJSONTyped(json, false);
}

export function EventUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'date': !exists(json, 'date') ? undefined : json['date'],
    };
}

export function EventUpdateDTOToJSON(value?: EventUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'content': value.content,
        'title': value.title,
        'location': value.location,
        'date': value.date,
    };
}

