/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { EventDTO } from './EventDTO';
import {
    EventDTOFromJSON,
    EventDTOFromJSONTyped,
    EventDTOToJSON,
} from './EventDTO';

/**
 * 
 * @export
 * @interface EventDTORequestResponse
 */
export interface EventDTORequestResponse {
    /**
     * 
     * @type {EventDTO}
     * @memberof EventDTORequestResponse
     */
    response?: EventDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof EventDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the EventDTORequestResponse interface.
 */
export function instanceOfEventDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventDTORequestResponseFromJSON(json: any): EventDTORequestResponse {
    return EventDTORequestResponseFromJSONTyped(json, false);
}

export function EventDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : EventDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function EventDTORequestResponseToJSON(value?: EventDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': EventDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

