/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackUpdateDTO
 */
export interface FeedbackUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    content?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackUpdateDTO
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    typeOfAppreciation?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackUpdateDTO
     */
    isUserExperienceEnjoyable?: boolean | null;
}

/**
 * Check if a given object implements the FeedbackUpdateDTO interface.
 */
export function instanceOfFeedbackUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackUpdateDTOFromJSON(json: any): FeedbackUpdateDTO {
    return FeedbackUpdateDTOFromJSONTyped(json, false);
}

export function FeedbackUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'typeOfAppreciation': !exists(json, 'typeOfAppreciation') ? undefined : json['typeOfAppreciation'],
        'isUserExperienceEnjoyable': !exists(json, 'isUserExperienceEnjoyable') ? undefined : json['isUserExperienceEnjoyable'],
    };
}

export function FeedbackUpdateDTOToJSON(value?: FeedbackUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'content': value.content,
        'rating': value.rating,
        'email': value.email,
        'name': value.name,
        'phoneNumber': value.phoneNumber,
        'typeOfAppreciation': value.typeOfAppreciation,
        'isUserExperienceEnjoyable': value.isUserExperienceEnjoyable,
    };
}

