/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface FeedbackDTO
 */
export interface FeedbackDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDTO
     */
    content?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackDTO
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDTO
     */
    typeOfAppreciation?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackDTO
     */
    isUserExperienceEnjoyable?: boolean;
    /**
     * 
     * @type {UserDTO}
     * @memberof FeedbackDTO
     */
    user?: UserDTO;
}

/**
 * Check if a given object implements the FeedbackDTO interface.
 */
export function instanceOfFeedbackDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackDTOFromJSON(json: any): FeedbackDTO {
    return FeedbackDTOFromJSONTyped(json, false);
}

export function FeedbackDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'typeOfAppreciation': !exists(json, 'typeOfAppreciation') ? undefined : json['typeOfAppreciation'],
        'isUserExperienceEnjoyable': !exists(json, 'isUserExperienceEnjoyable') ? undefined : json['isUserExperienceEnjoyable'],
        'user': !exists(json, 'user') ? undefined : UserDTOFromJSON(json['user']),
    };
}

export function FeedbackDTOToJSON(value?: FeedbackDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
        'rating': value.rating,
        'typeOfAppreciation': value.typeOfAppreciation,
        'isUserExperienceEnjoyable': value.isUserExperienceEnjoyable,
        'user': UserDTOToJSON(value.user),
    };
}

