/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackAddDTO
 */
export interface FeedbackAddDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    content?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackAddDTO
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    typeOfAppreciation?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackAddDTO
     */
    isUserExperienceEnjoyable?: boolean;
}

/**
 * Check if a given object implements the FeedbackAddDTO interface.
 */
export function instanceOfFeedbackAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackAddDTOFromJSON(json: any): FeedbackAddDTO {
    return FeedbackAddDTOFromJSONTyped(json, false);
}

export function FeedbackAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'typeOfAppreciation': !exists(json, 'typeOfAppreciation') ? undefined : json['typeOfAppreciation'],
        'isUserExperienceEnjoyable': !exists(json, 'isUserExperienceEnjoyable') ? undefined : json['isUserExperienceEnjoyable'],
    };
}

export function FeedbackAddDTOToJSON(value?: FeedbackAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'content': value.content,
        'rating': value.rating,
        'email': value.email,
        'name': value.name,
        'phoneNumber': value.phoneNumber,
        'typeOfAppreciation': value.typeOfAppreciation,
        'isUserExperienceEnjoyable': value.isUserExperienceEnjoyable,
    };
}

