/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { LikeDTO } from './LikeDTO';
import {
    LikeDTOFromJSON,
    LikeDTOFromJSONTyped,
    LikeDTOToJSON,
} from './LikeDTO';

/**
 * 
 * @export
 * @interface LikeDTOListRequestResponse
 */
export interface LikeDTOListRequestResponse {
    /**
     * 
     * @type {Array<LikeDTO>}
     * @memberof LikeDTOListRequestResponse
     */
    readonly response?: Array<LikeDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LikeDTOListRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the LikeDTOListRequestResponse interface.
 */
export function instanceOfLikeDTOListRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LikeDTOListRequestResponseFromJSON(json: any): LikeDTOListRequestResponse {
    return LikeDTOListRequestResponseFromJSONTyped(json, false);
}

export function LikeDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeDTOListRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(LikeDTOFromJSON)),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LikeDTOListRequestResponseToJSON(value?: LikeDTOListRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

