/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { LikeDTO } from './LikeDTO';
import {
    LikeDTOFromJSON,
    LikeDTOFromJSONTyped,
    LikeDTOToJSON,
} from './LikeDTO';

/**
 * 
 * @export
 * @interface LikeDTORequestResponse
 */
export interface LikeDTORequestResponse {
    /**
     * 
     * @type {LikeDTO}
     * @memberof LikeDTORequestResponse
     */
    response?: LikeDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LikeDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the LikeDTORequestResponse interface.
 */
export function instanceOfLikeDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LikeDTORequestResponseFromJSON(json: any): LikeDTORequestResponse {
    return LikeDTORequestResponseFromJSONTyped(json, false);
}

export function LikeDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : LikeDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LikeDTORequestResponseToJSON(value?: LikeDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': LikeDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

