/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
} from './Post';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Like
 */
export interface Like {
    /**
     * 
     * @type {string}
     * @memberof Like
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Like
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Like
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Like
     */
    postId?: string;
    /**
     * 
     * @type {Post}
     * @memberof Like
     */
    post?: Post;
    /**
     * 
     * @type {string}
     * @memberof Like
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof Like
     */
    user?: User;
}

/**
 * Check if a given object implements the Like interface.
 */
export function instanceOfLike(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LikeFromJSON(json: any): Like {
    return LikeFromJSONTyped(json, false);
}

export function LikeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Like {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'postId': !exists(json, 'postId') ? undefined : json['postId'],
        'post': !exists(json, 'post') ? undefined : PostFromJSON(json['post']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function LikeToJSON(value?: Like | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'postId': value.postId,
        'post': PostToJSON(value.post),
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

