/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { PostDTOPagedResponse } from './PostDTOPagedResponse';
import {
    PostDTOPagedResponseFromJSON,
    PostDTOPagedResponseFromJSONTyped,
    PostDTOPagedResponseToJSON,
} from './PostDTOPagedResponse';

/**
 * 
 * @export
 * @interface PostDTOPagedResponseRequestResponse
 */
export interface PostDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {PostDTOPagedResponse}
     * @memberof PostDTOPagedResponseRequestResponse
     */
    response?: PostDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof PostDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the PostDTOPagedResponseRequestResponse interface.
 */
export function instanceOfPostDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostDTOPagedResponseRequestResponseFromJSON(json: any): PostDTOPagedResponseRequestResponse {
    return PostDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function PostDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : PostDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function PostDTOPagedResponseRequestResponseToJSON(value?: PostDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': PostDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

