/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostUpdateDTO
 */
export interface PostUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof PostUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PostUpdateDTO
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostUpdateDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the PostUpdateDTO interface.
 */
export function instanceOfPostUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostUpdateDTOFromJSON(json: any): PostUpdateDTO {
    return PostUpdateDTOFromJSONTyped(json, false);
}

export function PostUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function PostUpdateDTOToJSON(value?: PostUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
        'userId': value.userId,
    };
}

