/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { PostDTO } from './PostDTO';
import {
    PostDTOFromJSON,
    PostDTOFromJSONTyped,
    PostDTOToJSON,
} from './PostDTO';

/**
 * 
 * @export
 * @interface PostDTORequestResponse
 */
export interface PostDTORequestResponse {
    /**
     * 
     * @type {PostDTO}
     * @memberof PostDTORequestResponse
     */
    response?: PostDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof PostDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the PostDTORequestResponse interface.
 */
export function instanceOfPostDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostDTORequestResponseFromJSON(json: any): PostDTORequestResponse {
    return PostDTORequestResponseFromJSONTyped(json, false);
}

export function PostDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : PostDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function PostDTORequestResponseToJSON(value?: PostDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': PostDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

