/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAddDTO
 */
export interface PostAddDTO {
    /**
     * 
     * @type {string}
     * @memberof PostAddDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof PostAddDTO
     */
    content?: string | null;
}

/**
 * Check if a given object implements the PostAddDTO interface.
 */
export function instanceOfPostAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostAddDTOFromJSON(json: any): PostAddDTO {
    return PostAddDTOFromJSONTyped(json, false);
}

export function PostAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function PostAddDTOToJSON(value?: PostAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'content': value.content,
    };
}

