/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserRequestResponse
 */
export interface UserRequestResponse {
    /**
     * 
     * @type {User}
     * @memberof UserRequestResponse
     */
    response?: User;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof UserRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the UserRequestResponse interface.
 */
export function instanceOfUserRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserRequestResponseFromJSON(json: any): UserRequestResponse {
    return UserRequestResponseFromJSONTyped(json, false);
}

export function UserRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : UserFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function UserRequestResponseToJSON(value?: UserRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': UserToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

